document.querySelectorAll('.check').forEach(button=>{button.addEventListener('click',()=>{const el=document.getElementById(button.dataset.target);if(el){el.classList.toggle('show');button.textContent=el.classList.contains('show')?'Hide answer':'Check answers'}})});
const essay=document.getElementById('essay'),count=document.getElementById('count');
if(essay&&count){essay.addEventListener('input',()=>{const words=essay.value.trim()?essay.value.trim().split(/\s+/).length:0;count.textContent=words})}
const sampleToggle=document.getElementById('sampleToggle'),sampleText=document.getElementById('sampleText');
if(sampleToggle&&sampleText){sampleToggle.addEventListener('click',()=>{const open=sampleText.style.display!=='none';sampleText.style.display=open?'none':'block';sampleToggle.textContent=open?'Open Sample Answer':'Hide Sample Answer'})}

// Extended Rewrite the Stages in IELTS Style practice
const buildBox=document.querySelector('.build-box');
if(buildBox){
  const extra=document.createElement('div');
  extra.className='exercise-grid';
  extra.innerHTML=`
    <div class="exercise"><span class="q">D</span><p>Rewrite using the passive voice: “Sulphur dioxide reacts with oxygen and water.”</p><input placeholder="Sulphur dioxide …"><div class="answer" id="r1">Model: <strong>Oxygen and water are reacted with by sulphur dioxide.</strong><br><small>More natural process-writing option: <strong>Sulphur dioxide reacts with oxygen and water to form new compounds.</strong></small></div><button class="check" data-target="r1">Check</button></div>
    <div class="exercise"><span class="q">E</span><p>Rewrite in a more formal process style: “Rain and dry particles put sulphur back on the Earth's surface.”</p><input placeholder="Sulphur is …"><div class="answer" id="r2">Model: <strong>Sulphur compounds are returned to the Earth's surface through wet and dry deposition.</strong></div><button class="check" data-target="r2">Check</button></div>
    <div class="exercise"><span class="q">F</span><p>Rewrite using <strong>be taken up by</strong>: “Plants absorb sulphate ions.”</p><input placeholder="Sulphate ions …"><div class="answer" id="r3">Model: <strong>Sulphate ions are taken up by plants.</strong></div><button class="check" data-target="r3">Check</button></div>
    <div class="exercise"><span class="q">G</span><p>Rewrite using <strong>be consumed by</strong>: “Animals consume plants containing sulphur.”</p><input placeholder="Plants …"><div class="answer" id="r4">Model: <strong>Plants containing sulphur are consumed by animals.</strong></div><button class="check" data-target="r4">Check</button></div>
    <div class="exercise"><span class="q">H</span><p>Combine the stages using <strong>after being</strong>: “Organic material is deposited. Microorganisms break it down.”</p><input placeholder="After being …"><div class="answer" id="r5">Model: <strong>After being deposited, organic material is broken down by microorganisms.</strong></div><button class="check" data-target="r5">Check</button></div>
    <div class="exercise"><span class="q">I</span><p>Rewrite using a participial clause: “Microorganisms break down organic material. They release sulphur compounds back into the soil and water.”</p><input placeholder="Microorganisms …, releasing …"><div class="answer" id="r6">Model: <strong>Microorganisms break down organic material, releasing sulphur compounds back into the soil and water.</strong></div><button class="check" data-target="r6">Check</button></div>
    <div class="exercise"><span class="q">J</span><p>Rewrite using a relative clause: “Some compounds return to the Earth's surface. These compounds are deposited through wet and dry deposition.”</p><input placeholder="Compounds which …"><div class="answer" id="r7">Model: <strong>Compounds which return to the Earth's surface are deposited through wet and dry deposition.</strong></div><button class="check" data-target="r7">Check</button></div>
    <div class="exercise"><span class="q">K</span><p>Rewrite with a clear sequence marker: “Sulphur is deposited. Plants then absorb sulphate ions.”</p><input placeholder="Following …"><div class="answer" id="r8">Model: <strong>Following deposition, plants absorb sulphate ions.</strong></div><button class="check" data-target="r8">Check</button></div>
    <div class="exercise"><span class="q">L</span><p>Rewrite as a compact final-stage sentence: “Sulphates are carried into rivers. They eventually reach the ocean.”</p><input placeholder="Some sulphates …"><div class="answer" id="r9">Model: <strong>Some sulphates are carried into rivers and ultimately reach the ocean through runoff.</strong></div><button class="check" data-target="r9">Check</button></div>`;
  buildBox.insertAdjacentElement('afterend',extra);
  extra.querySelectorAll('.check').forEach(button=>button.addEventListener('click',()=>{const el=document.getElementById(button.dataset.target);if(el){el.classList.toggle('show');button.textContent=el.classList.contains('show')?'Hide answer':'Check answers'}}));
}

document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const target=document.querySelector(a.getAttribute('href'));if(target){e.preventDefault();target.scrollIntoView({behavior:'smooth',block:'start'})}}));
